version: "3"
services:
  myurls:
    build: .
    container_name: myurls
    restart: always
    env_file: .env
    environment:
      MYURLS_STORAGE_REDIS_ADDR: myurls-redis:6379
    ports:
      - "${MYURLS_SERVER_PORT}:${MYURLS_SERVER_PORT}"
    volumes:
      - ./data/myurls/logs:/app/logs
      - ./conf:/app/conf
    depends_on:
      - myurls-redis

  myurls-redis:
    image: "redis:7"
    container_name: myurls-redis
    restart: always
    volumes:
      - ./data/redis:/data
    expose:
      - "6379"
