version: "3"
services:
  myurls:
    build: .
    container_name: myurls
    restart: always
    env_file: .env
    ports:
      - "${MYURLS_SERVER_PORT}:${MYURLS_SERVER_PORT}"
    volumes:
      - ./data/myurls/logs:/app/logs      
    depends_on:
      - myurls-redis
    entrypoint: ["/app/myurls", "-domain", "${MYURLS_SERVER_DOMAIN}", "-conn", myurls-redis:6379]

  myurls-redis:
    image: "redis:7"
    container_name: myurls-redis
    restart: always
    volumes:
      - ./data/redis:/data
    expose:
      - "6379"
